export { default as childcount } from './childcount.json'
export { default as jobs } from './jobs.json'
export { default as aspirations } from './aspirations.json'
export { default as likes } from './likes.json'
export { default as kidsage } from './kidsage.json'
export { default as extras } from './extras.json'